### ISSUE TITLE
Add validation to the inputs

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-help#2]
- [ ] Search
  - To guarantee that at least one input has data
- [ ] Add/Edit an institution
  - What inputs are required?
  - Valid types?
  - Valid formatting?

_We'll need to make sure that we match any of these details with the back-end implementation._

**Comment by keileyo** [comment]
Validation on the inputs:

- LEI should be 20 characters (letters & numbers)
- Tax ID should be 10 characters with a dash after the 2nd character (ex 99-9999999)
- Disable the add button until LEI, name, agency code, tax-id have been added. **note:** i removed email domain from the list of required fields for an addition. In rare cases, we don't add an email domain to institutions because the FI uses only a public email domain (like verizon.net) and in those cases, we just associate the user with the institution in keycloak manually.
